#:schema node_modules/wrangler/config-schema.json
name = "breadbot"
main = "src/index.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
preview_urls = true
route = "breadbot"

# Runs the scheduled() function on this schedule
[triggers]
crons = ["0 23 * * TUE,WED,FRI"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
